// This Source Code Form is subject to the terms of the Mozilla Public License,
// v. 2.0. If a copy of the MPL was not distributed with this file, You can
// obtain one at http://mozilla.org/MPL/2.0/.

package lib

import (
	"math"
	"os"
	"time"

	"github.com/islisp-dev/iris/runtime/core"
)

var Time time.Time

var TopLevel = core.NewEnvironment(
	core.NewStream(os.Stdin, nil, core.CharacterClass),
	core.NewStream(nil, os.Stdout, core.CharacterClass),
	core.NewStream(nil, os.Stderr, core.CharacterClass),
	core.DefaultHandler,
)

func defclass(name string, class core.Class) {
	symbol := core.NewSymbol(name)
	TopLevel.Class.Define(symbol, class)
}

func defspecial(name string, function interface{}) {
	symbol := core.NewSymbol(name)
	TopLevel.Special.Define(symbol, core.NewFunction(func2symbol(function), function))
}

func defun(name string, function interface{}) {
	symbol := core.NewSymbol(name)
	TopLevel.Function.Define(symbol, core.NewFunction(symbol, function))
}

func defgeneric(name string, function interface{}) {
	symbol := core.NewSymbol(name)
	lambdaList, _ := List(TopLevel, core.NewSymbol("FIRST"), core.NewSymbol("&REST"), core.NewSymbol("REST"))
	generic := core.NewGenericFunction(symbol, lambdaList, T, core.GenericFunctionClass)
	generic.(*core.GenericFunction).AddMethod(nil, lambdaList, []core.Class{core.StandardClassClass}, core.NewFunction(symbol, function))
	TopLevel.Function.Define(symbol, generic)
}

func defglobal(name string, value core.Instance) {
	symbol := core.NewSymbol(name)
	TopLevel.Variable.Define(symbol, value)
}

func init() {
	defun("EVAL", Eval) // This function is for verificaiton. DO NOT USE.
	defglobal("*PI*", core.Float(math.Pi))
	defglobal("*MOST-POSITIVE-FLOAT*", MostPositiveFloat)
	defglobal("*MOST-NEGATIVE-FLOAT*", MostNegativeFloat)
	defun("-", Substruct)
	defun("+", Add)
	defun("*", Multiply)
	defun("<", NumberLessThan)
	defun("<=", NumberLessThanOrEqual)
	defun("=", NumberEqual)
	defun("/=", NumberNotEqual)
	defun(">", NumberGreaterThan)
	defun(">=", NumberGreaterThanOrEqual)
	defspecial("QUASIQUOTE", Quasiquote)
	defun("ABS", Abs)
	defspecial("AND", And)
	defun("APPEND", Append)
	defun("APPLY", Apply)
	defun("ARRAY-DIMENSIONS", ArrayDimensions)
	defun("AREF", Aref)
	defun("ASSOC", Assoc)
	// TODO: defspecial2("ASSURE", Assure)
	defun("ATAN", Atan)
	defun("ATAN2", Atan2)
	defun("ATANH", Atanh)
	defun("BASIC-ARRAY*-P", BasicArrayStarP)
	defun("BASIC-ARRAY-P", BasicArrayP)
	defun("BASIC-VECTOR-P", BasicVectorP)
	defspecial("BLOCK", Block)
	defun("CAR", Car)
	defspecial("CASE", Case)
	defspecial("CASE-USING", CaseUsing)
	defspecial("CATCH", Catch)
	defun("CDR", Cdr)
	defun("CEILING", Ceiling)
	defun("CERROR", Cerror)
	defun("CHAR-INDEX", CharIndex)
	defun("CHAR/=", CharNotEqual)
	defun("CHAR<", CharLessThan)
	defun("CHAR<=", CharLessThanOrEqual)
	defun("CHAR=", CharEqual)
	defun("CHAR>", CharGreaterThan)
	defun("CHAR>=", CharGreaterThanOrEqual)
	defun("CHARACTERP", Characterp)
	defspecial("CLASS", Class)
	defun("CLASS-OF", ClassOf)
	defun("CLOSE", Close)
	// SKIP defun2("COERCION", Coercion)
	defspecial("COND", Cond)
	defun("CONDITION-CONTINUABLE", ConditionContinuable)
	defun("CONS", Cons)
	defun("CONSP", Consp)
	defun("CONTINUE-CONDITION", ContinueCondition)
	defspecial("CONVERT", Convert)
	defun("COS", Cos)
	defun("COSH", Cosh)
	defgeneric("CREATE", Create) //TODO Change to generic function
	defun("CREATE-ARRAY", CreateArray)
	defun("CREATE-LIST", CreateList)
	defun("CREATE-STRING", CreateString)
	defun("CREATE-STRING-INPUT-STREAM", CreateStringInputStream)
	defun("CREATE-STRING-OUTPUT-STREAM", CreateStringOutputStream)
	defun("CREATE-VECTOR", CreateVector)
	defspecial("DEFCLASS", Defclass)
	defspecial("DEFCONSTANT", Defconstant)
	defspecial("DEFDYNAMIC", Defdynamic)
	defspecial("DEFGENERIC", Defgeneric)
	defspecial("DEFMETHOD", Defmethod)
	defspecial("DEFGLOBAL", Defglobal)
	defspecial("DEFMACRO", Defmacro)
	defspecial("DEFUN", Defun)
	defun("DIV", Div)
	defspecial("DYNAMIC", Dynamic)
	defspecial("DYNAMIC-LET", DynamicLet)
	defun("ELT", Elt)
	defun("EQ", Eq)
	defun("EQL", Eql)
	defun("EQUAL", Equal)
	defun("ERROR", Error)
	defun("ERROR-OUTPUT", ErrorOutput)
	defun("EXP", Exp)
	defun("EXPT", Expt)
	// TODO defun2("FILE-LENGTH", FileLength)
	// TODO defun2("FILE-POSITION", FilePosition)
	defun("FINISH-OUTPUT", FinishOutput)
	defspecial("FLET", Flet)
	defun("FLOAT", Float)
	defun("FLOATP", Floatp)
	defun("FLOOR", Floor)
	defspecial("FOR", For)
	defun("FORMAT", Format)
	defun("FORMAT-CHAR", FormatChar)
	defun("FORMAT-FLOAT", FormatFloat)
	defun("FORMAT-FRESH-LINE", FormatFreshLine)
	defun("FORMAT-INTEGER", FormatInteger)
	defun("FORMAT-OBJECT", FormatObject)
	defun("FORMAT-TAB", FormatTab)
	defun("FUNCALL", Funcall)
	defspecial("FUNCTION", Function)
	defun("FUNCTIONP", Functionp)
	defun("GAREF", Garef)
	defun("GCD", Gcd)
	defun("GENERAL-ARRAY*-P", GeneralArrayStarP)
	defun("GENERAL-VECTOR-P", GeneralVectorP)
	defun("GENERIC-FUNCTION-P", GenericFunctionP)
	defun("GENSYM", Gensym)
	defun("GET-INTERNAL-REAL-TIME", GetInternalRealTime)
	defun("GET-INTERNAL-RUN-TIME", GetInternalRunTime)
	defun("GET-OUTPUT-STREAM-STRING", GetOutputStreamString)
	defun("GET-UNIVERSAL-TIME", GetUniversalTime)
	defspecial("GO", Go)
	defun("IDENTITY", Identity)
	defspecial("IF", If)
	defspecial("IGNORE-ERRORS", IgnoreErrors)
	defgeneric("INITIALIZE-OBJECT", InitializeObject) // TODO change generic function
	defun("INPUT-STREAM-P", InputStreamP)
	defun("INSTANCEP", Instancep)
	defun("INTEGERP", Integerp)
	defun("INTERNAL-TIME-UNITS-PER-SECOND", InternalTimeUnitsPerSecond)
	defun("ISQRT", Isqrt)
	defspecial("LABELS", Labels)
	defspecial("LAMBDA", Lambda)
	defun("LCM", Lcm)
	defun("LENGTH", Length)
	defspecial("LET", Let)
	defspecial("LET*", LetStar)
	defun("LIST", List)
	defun("LISTP", Listp)
	defun("LOG", Log)
	defun("MAP-INTO", MapInto)
	defun("MAPC", Mapc)
	defun("MAPCAN", Mapcan)
	defun("MAPCAR", Mapcar)
	defun("MAPCON", Mapcon)
	defun("MAPL", Mapl)
	defun("MAPLIST", Maplist)
	defun("MAX", Max)
	defun("MEMBER", Member)
	defun("MIN", Min)
	defun("MOD", Mod)
	defglobal("NI-L", Nil)
	defun("NOT", Not)
	defun("NREVERSE", Nreverse)
	defun("NULL", Null)
	defun("NUMBERP", Numberp)
	defun("OPEN-INPUT-FILE", OpenInputFile)
	defun("OPEN-IO-FILE", OpenIoFile)
	defun("OPEN-OUTPUT-FILE", OpenOutputFile)
	defun("OPEN-STREAM-P", OpenStreamP)
	defspecial("OR", Or)
	// defun("FLUSH-OUTPUT", FlushOutput)
	defun("OUTPUT-STREAM-P", OutputStreamP)
	defun("PARSE-NUMBER", ParseNumber)
	defun("PREVIEW-CHAR", PreviewChar)
	defun("PROBE-FILE", ProbeFile)
	defspecial("PROGN", Progn)
	defun("PROPERTY", Property)
	defspecial("QUASIQUOTE", Quasiquote)
	defspecial("QUOTE", Quote)
	defun("QUOTIENT", Quotient)
	defun("READ", Read)
	defun("READ-BYTE", ReadByte)
	defun("READ-CHAR", ReadChar)
	defun("READ-LINE", ReadLine)
	defun("REMOVE-PROPERTY", RemoveProperty)
	defun("REPORT-CONDITION", ReportCondition)
	defspecial("RETURN-FROM", ReturnFrom)
	defun("REVERSE", Reverse)
	defun("ROUND", Round)
	defun("SET-AREF", SetAref)
	defun("(SETF AREF)", SetAref)
	defun("SET-CAR", SetCar)
	defun("(SETF CAR)", SetCar)
	defun("SET-CDR", SetCdr)
	defun("(SETF CDR)", SetCdr)
	defun("SET-DYNAMIC", SetDynamic)
	defun("(SETF DYNAMIC)", SetDynamic)
	defun("SET-ELT", SetElt)
	defun("(SETF ELT)", SetElt)
	// TODO defun2("SET-FILE-POSITION", SetFilePosition)
	defun("SET-GAREF", SetGaref)
	defun("(SETF GAREF)", SetGaref)
	defun("SET-PROPERTY", SetProperty)
	defun("(SETF PROPERTY)", SetProperty)
	defspecial("SETF", Setf)
	defspecial("SETQ", Setq)
	defun("SIGNAL-CONDITION", SignalCondition)
	defun("SIN", Sin)
	defun("SINH", Sinh)
	defun("SQRT", Sqrt)
	defun("STANDARD-INPUT", StandardInput)
	defun("STANDARD-OUTPUT", StandardOutput)
	defun("STREAM-READY-P", StreamReadyP)
	defun("STREAMP", Streamp)
	defun("STRING-APPEND", StringAppend)
	defun("STRING-INDEX", StringIndex)
	defun("STRING/=", StringNotEqual)
	defun("STRING>", StringGreaterThan)
	defun("STRING>=", StringGreaterThanOrEqual)
	defun("STRING=", StringEqual)
	defun("STRING<", StringLessThan)
	defun("STRING<=", StringLessThanOrEqual)
	defun("STRINGP", Stringp)
	defun("SUBCLASSP", Subclassp)
	defun("SUBSEQ", Subseq)
	defun("SYMBOLP", Symbolp)
	defglobal("T", T)
	defspecial("TAGBODY", Tagbody)
	defspecial("TAN", Tan)
	defspecial("TANH", Tanh)
	// TODO defspecial2("THE", The)
	defspecial("THROW", Throw)
	defun("TRUNCATE", Truncate)
	defspecial("UNWIND-PROTECT", UnwindProtect)
	defun("VECTOR", Vector)
	defspecial("WHILE", While)
	defspecial("WITH-ERROR-OUTPUT", WithErrorOutput)
	defspecial("WITH-HANDLER", WithHandler)
	defspecial("WITH-OPEN-INPUT-FILE", WithOpenInputFile)
	defspecial("WITH-OPEN-OUTPUT-FILE", WithOpenOutputFile)
	defspecial("WITH-STANDARD-INPUT", WithStandardInput)
	defspecial("WITH-STANDARD-OUTPUT", WithStandardOutput)
	defun("WRITE-BYTE", WriteByte)
	defclass("<OBJECT>", core.ObjectClass)
	defclass("<BUILT-IN-CLASS>", core.BuiltInClassClass)
	defclass("<STANDARD-CLASS>", core.StandardClassClass)
	defclass("<BASIC-ARRAY>", core.BasicArrayClass)
	defclass("<BASIC-ARRAY-STAR>", core.BasicArrayStarClass)
	defclass("<GENERAL-ARRAY-STAR>", core.GeneralArrayStarClass)
	defclass("<BASIC-VECTOR>", core.BasicVectorClass)
	defclass("<GENERAL-VECTOR>", core.GeneralVectorClass)
	defclass("<STRING>", core.StringClass)
	defclass("<CHARACTER>", core.CharacterClass)
	defclass("<FUNCTION>", core.FunctionClass)
	defclass("<GENERIC-FUNCTION>", core.GenericFunctionClass)
	defclass("<STANDARD-GENERIC-FUNCTION>", core.StandardGenericFunctionClass)
	defclass("<LIST>", core.ListClass)
	defclass("<CONS>", core.ConsClass)
	defclass("<NULL>", core.NullClass)
	defclass("<SYMBOL>", core.SymbolClass)
	defclass("<NUMBER>", core.NumberClass)
	defclass("<INTEGER>", core.IntegerClass)
	defclass("<FLOAT>", core.FloatClass)
	defclass("<SERIOUS-CONDITION>", core.SeriousConditionClass)
	defclass("<ERROR>", core.ErrorClass)
	defclass("<ARITHMETIC-ERROR>", core.ArithmeticErrorClass)
	defclass("<DIVISION-BY-ZERO>", core.DivisionByZeroClass)
	defclass("<FLOATING-POINT-ONDERFLOW>", core.FloatingPointOnderflowClass)
	defclass("<FLOATING-POINT-UNDERFLOW>", core.FloatingPointUnderflowClass)
	defclass("<CONTROL-ERROR>", core.ControlErrorClass)
	defclass("<PARSE-ERROR>", core.ParseErrorClass)
	defclass("<PROGRAM-ERROR>", core.ProgramErrorClass)
	defclass("<DOMAIN-ERROR>", core.DomainErrorClass)
	defclass("<UNDEFINED-ENTITY>", core.UndefinedEntityClass)
	defclass("<UNBOUND-VARIABLE>", core.UnboundVariableClass)
	defclass("<UNDEFINED-FUNCTION>", core.UndefinedFunctionClass)
	defclass("<SIMPLE-ERROR>", core.SimpleErrorClass)
	defclass("<STREAM-ERROR>", core.StreamErrorClass)
	defclass("<END-OF-STREAM>", core.EndOfStreamClass)
	defclass("<STORAGE-EXHAUSTED>", core.StorageExhaustedClass)
	defclass("<STANDARD-OBJECT>", core.StandardObjectClass)
	defclass("<STREAM>", core.StreamClass)

	defun("ARITHMETIC-ERROR-OPERATION", CreateReader(core.ArithmeticErrorClass, "OPERATION"))
	defun("ARITHMETIC-ERROR-OPERANDS", CreateReader(core.ArithmeticErrorClass, "OPERANDS"))
	defun("DOMAIN-ERROR-OBJECT", CreateReader(core.DomainErrorClass, "OPERANDS"))
	defun("DOMAIN-ERROR-EXPECTED-CLASS", CreateReader(core.DomainErrorClass, "EXPECTED-CLASS"))
	defun("PARSE-ERROR-STRING", CreateReader(core.ParseErrorClass, "STRING"))
	defun("PARSE-ERROR-EXPECTED-CLASS", CreateReader(core.ParseErrorClass, "EXPECTED-CLASS"))
	defun("SIMPLE-ERROR-FORMAT-STRING", CreateReader(core.SimpleErrorClass, "FORMAT-STRING"))
	defun("SIMPLE-ERROR-FORMAT-ARGUMENTS", CreateReader(core.SimpleErrorClass, "FORMAT-ARGUMENTS"))
	defun("STREAM-ERROR-STREAM", CreateReader(core.StreamErrorClass, "STREAM"))
	defun("UNDEFINED-ENTITY-NAME", CreateReader(core.SimpleErrorClass, "NAME"))
	defun("UNDEFINED-ENTITY-NAMESPACE", CreateReader(core.StreamErrorClass, "NAMESPACE"))
	Time = time.Now()
}
