(progn (defgeneric f (x y z) (:method-combination nil))
(defclass C1 () ())
(defmethod f ((x C1) (y C1) (z C1))  
                 (format (standard-output) "call with ~A ~A ~A~%" 'C1 'C1 'C1))
(defclass C2 (C1) ())
(defmethod f ((x C2) (y C2) (z C2))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C2 'C2 'C2)
                 (f (create (class C2))
                    (create (class C2))
                    (create (class C1))))
(defmethod f ((x C2) (y C2) (z C1))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C2 'C2 'C1)
                 (f (create (class C2))
                    (create (class C1))
                    (create (class C2))))
(defmethod f ((x C2) (y C1) (z C2))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C2 'C1 'C2)
                 (f (create (class C1))
                    (create (class C2))
                    (create (class C2))))
(defmethod f ((x C1) (y C2) (z C2))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C1 'C2 'C2)
                 (f (create (class C2))
                    (create (class C1))
                    (create (class C1))))
(defmethod f ((x C2) (y C1) (z C1))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C2 'C1 'C1)
                 (f (create (class C1))
                    (create (class C2))
                    (create (class C1))))
(defmethod f ((x C1) (y C2) (z C1))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C1 'C2 'C1)
                 (f (create (class C1))
                    (create (class C1))
                    (create (class C2))))
(defmethod f ((x C1) (y C1) (z C2))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C1 'C1 'C2)
                 (f (create (class C1))
                    (create (class C1))
                    (create (class C1))))
(defmethod f ((x C1) (y C1) (z C1))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C1 'C1 'C1)
                 (if (next-method-p) (call-next-method)))
(defclass C3 (C2) ())
(defmethod f ((x C3) (y C3) (z C3))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C3 'C3 'C3)
                 (f (create (class C3))
                    (create (class C3))
                    (create (class C2))))
(defmethod f ((x C3) (y C3) (z C2))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C3 'C3 'C2)
                 (f (create (class C3))
                    (create (class C2))
                    (create (class C3))))
(defmethod f ((x C3) (y C2) (z C3))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C3 'C2 'C3)
                 (f (create (class C2))
                    (create (class C3))
                    (create (class C3))))
(defmethod f ((x C2) (y C3) (z C3))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C2 'C3 'C3)
                 (f (create (class C3))
                    (create (class C2))
                    (create (class C2))))
(defmethod f ((x C3) (y C2) (z C2))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C3 'C2 'C2)
                 (f (create (class C2))
                    (create (class C3))
                    (create (class C2))))
(defmethod f ((x C2) (y C3) (z C2))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C2 'C3 'C2)
                 (f (create (class C2))
                    (create (class C2))
                    (create (class C3))))
(defmethod f ((x C2) (y C2) (z C3))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C2 'C2 'C3)
                 (f (create (class C2))
                    (create (class C2))
                    (create (class C2))))
(defmethod f ((x C2) (y C2) (z C2))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C2 'C2 'C2)
                 (if (next-method-p) (call-next-method)))
(defclass C (C3) ())
(defmethod f ((x C) (y C) (z C))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C 'C 'C)
                 (f (create (class C))
                    (create (class C))
                    (create (class C3))))
(defmethod f ((x C) (y C) (z C3))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C 'C 'C3)
                 (f (create (class C))
                    (create (class C3))
                    (create (class C))))
(defmethod f ((x C) (y C3) (z C))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C 'C3 'C)
                 (f (create (class C3))
                    (create (class C))
                    (create (class C))))
(defmethod f ((x C3) (y C) (z C))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C3 'C 'C)
                 (f (create (class C))
                    (create (class C3))
                    (create (class C3))))
(defmethod f ((x C) (y C3) (z C3))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C 'C3 'C3)
                 (f (create (class C3))
                    (create (class C))
                    (create (class C3))))
(defmethod f ((x C3) (y C) (z C3))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C3 'C 'C3)
                 (f (create (class C3))
                    (create (class C3))
                    (create (class C))))
(defmethod f ((x C3) (y C3) (z C))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C3 'C3 'C)
                 (f (create (class C3))
                    (create (class C3))
                    (create (class C3))))
(defmethod f ((x C3) (y C3) (z C3))
                 (format (standard-output) "call with ~A ~A ~A~%" 'C3 'C3 'C3)
                 (if (next-method-p) (call-next-method)))
(f (create (class c)) (create (class c)) (create (class c))))
