(defgeneric f (x y) (:method-combination nil))
(defclass C0 () ())
(defmethod f ((x C0) (y C0)) nil)
(defclass C1 () ())
(defmethod f ((x C1) (y C1)) nil)
(defclass C (C0 C1) ())
(defmethod f ((x C1) (y C0))
                 (format (standard-output) "call with ~A ~A~%" 'C1 'C0)
                 (if (next-method-p) (call-next-method)))
(defmethod f ((x C0) (y C1))
                 (format (standard-output) "call with ~A ~A~%" 'C0 'C1)
                 (f (create (class C1)) (create (class C))))
(f (create (class c)) (create (class c)))
